### PR TITLE
Selectable add support for begin(), end() widget methods Issue #46

### PR DESCRIPTION
**Pull request by fdezmc**
My proposal for issue #46

### CODE REVIEW

**Comment by fdezmc** [comment]
Hi @samdark, added the line to CHANGELOG and built a test. But my test can't pass as much as `\yii\base\Widget` is not on `yii2-jui` project. Don't know how to make a test this without rendering the view. Any idea?

**Comment by samdark** [comment]
Nope. See https://github.com/yiisoft/yii2-jui/blob/master/tests/DatePickerTest.php

**Comment by fdezmc** [comment]
Test added and passed. Thanks for your comments.

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
